/* eslint-disable */
/**
 * This file was automatically generated.
 * DO NOT MODIFY IT BY HAND.
 */

export interface VscodeProduct {
  /**
   * API proposals that the respective extensions can freely use.
   */
  extensionEnabledApiProposals?: {
    [k: string]: (
      | "aiRelatedInformation"
      | "authGetSessions"
      | "authSession"
      | "canonicalUriProvider"
      | "chat"
      | "chatAgents"
      | "chatProvider"
      | "chatRequestAccess"
      | "chatSlashCommands"
      | "chatVariables"
      | "codiconDecoration"
      | "commentsDraftState"
      | "contribCommentEditorActionsMenu"
      | "contribCommentPeekContext"
      | "contribCommentThreadAdditionalMenu"
      | "contribEditSessions"
      | "contribEditorContentMenu"
      | "contribLabelFormatterWorkspaceTooltip"
      | "contribMenuBarHome"
      | "contribMergeEditorMenus"
      | "contribNotebookStaticPreloads"
      | "contribRemoteHelp"
      | "contribShareMenu"
      | "contribStatusBarItems"
      | "contribViewsRemote"
      | "contribViewsWelcome"
      | "customEditorMove"
      | "debugFocus"
      | "diffCommand"
      | "diffContentOptions"
      | "documentFiltersExclusive"
      | "documentPaste"
      | "dropMetadata"
      | "editSessionIdentityProvider"
      | "editorInsets"
      | "extensionRuntime"
      | "extensionsAny"
      | "externalUriOpener"
      | "fileComments"
      | "fileSearchProvider"
      | "findTextInFiles"
      | "fsChunks"
      | "handleIssueUri"
      | "idToken"
      | "inlineCompletionsAdditions"
      | "interactive"
      | "interactiveUserActions"
      | "interactiveWindow"
      | "ipc"
      | "mappedEditsProvider"
      | "notebookCellExecutionState"
      | "notebookControllerAffinityHidden"
      | "notebookDeprecated"
      | "notebookExecution"
      | "notebookKernelSource"
      | "notebookLiveShare"
      | "notebookMessaging"
      | "notebookMime"
      | "portsAttributes"
      | "profileContentHandlers"
      | "quickDiffProvider"
      | "quickPickItemTooltip"
      | "quickPickSortByLabel"
      | "readonlyMessage"
      | "resolvers"
      | "saveEditor"
      | "scmActionButton"
      | "scmHistoryProvider"
      | "scmSelectedProvider"
      | "scmTextDocument"
      | "scmValidation"
      | "shareProvider"
      | "showLocal"
      | "tabInputTextMerge"
      | "taskPresentationGroup"
      | "telemetry"
      | "terminalDataWriteEvent"
      | "terminalDimensions"
      | "terminalExecuteCommandEvent"
      | "terminalQuickFixProvider"
      | "terminalSelection"
      | "testCoverage"
      | "testMessageContextValue"
      | "testObserver"
      | "textSearchProvider"
      | "timeline"
      | "tokenInformation"
      | "treeViewActiveItem"
      | "treeViewMarkdownMessage"
      | "treeViewReveal"
      | "tunnelFactory"
      | "tunnels"
      | "windowActivity"
      | "workspaceTrust"
    )[];
  };
}
